-- Add bodyweight exercises including squats, lunges, and push-ups
INSERT INTO exercises (name, primary_muscle_group, secondary_muscle_groups, equipment, focus_areas, is_public, is_public_mission_allowed, instructions_setup, instructions_execution, instructions_tips)
VALUES 
  ('Bodyweight Squat', 'Quadriceps', ARRAY['Glutes', 'Hamstrings', 'Core']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Legs', 'Lower Body', 'Functional']::text[], true, true, 'Stand with feet shoulder-width apart, toes slightly pointed out.', 'Bend at knees and hips, lowering until thighs are parallel. Push through heels to stand.', 'Keep chest up and core tight. Drive knees out over toes.'),
  ('Bodyweight Lunge', 'Quadriceps', ARRAY['Glutes', 'Hamstrings']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Legs', 'Lower Body', 'Functional']::text[], true, true, 'Stand tall with feet hip-width apart.', 'Step forward, lowering back knee toward ground. Push through front heel to return.', 'Keep front knee over ankle. Alternate legs for each rep.'),
  ('Bodyweight Split Squat', 'Quadriceps', ARRAY['Glutes', 'Hamstrings']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Legs', 'Lower Body']::text[], true, true, 'Stand in a staggered stance, feet hip-width apart.', 'Lower back knee toward floor, keeping front shin vertical. Drive up through front foot.', 'Do all reps on one side, then switch.'),
  ('Push Up', 'Chest', ARRAY['Triceps', 'Anterior Deltoids', 'Core']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Upper Body', 'Push', 'Chest']::text[], true, true, 'Start in plank position, hands slightly wider than shoulders.', 'Lower chest toward floor, then push back up. Keep body in straight line.', 'Squeeze glutes and brace core. Full range of motion.'),
  ('Diamond Push Up', 'Triceps', ARRAY['Chest', 'Anterior Deltoids']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Arms', 'Push', 'Triceps']::text[], true, true, 'Form a diamond shape with hands under chest.', 'Lower chest to hands, elbows tracking back. Push up explosively.', 'Harder than regular push-ups. Scale to knees if needed.'),
  ('Pike Push Up', 'Deltoids', ARRAY['Triceps', 'Upper Chest']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Shoulders', 'Push']::text[], true, true, 'Start in downward dog position, hips high.', 'Bend elbows to lower head toward floor. Push back up.', 'Great shoulder builder without weights.'),
  ('Glute Bridge', 'Glutes', ARRAY['Hamstrings', 'Core']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Legs', 'Glutes', 'Lower Body']::text[], true, true, 'Lie on back, knees bent, feet flat on floor.', 'Drive through heels, lifting hips until body forms straight line. Squeeze glutes at top.', 'Hold the top position for 1-2 seconds.'),
  ('Plank', 'Core', ARRAY['Shoulders', 'Glutes']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Core', 'Stability']::text[], true, true, 'Start in forearm plank position, elbows under shoulders.', 'Hold position, keeping body in straight line from head to heels.', 'Breathe steadily. Count reps as seconds held.'),
  ('Mountain Climber', 'Core', ARRAY['Hip Flexors', 'Shoulders']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Core', 'Cardio', 'HIIT']::text[], true, true, 'Start in high plank position.', 'Drive knees toward chest alternately in running motion.', 'Keep hips low and move explosively.'),
  ('Burpee', 'Full Body', ARRAY['Chest', 'Quadriceps', 'Core']::text[], ARRAY['BODYWEIGHT']::equipment_type[], ARRAY['Full Body', 'Cardio', 'HIIT']::text[], true, true, 'Stand with feet shoulder-width apart.', 'Drop to push-up, perform push-up, jump feet to hands, explode upward.', 'Full extension at the top. Modify by stepping instead of jumping.'),
  ('Bulgarian Split Squat', 'Quadriceps', ARRAY['Glutes', 'Hamstrings']::text[], ARRAY['BODYWEIGHT', 'BENCH']::equipment_type[], ARRAY['Legs', 'Lower Body', 'Unilateral']::text[], true, true, 'Place rear foot on bench behind you, hop forward into lunge stance.', 'Lower until front thigh is parallel. Drive through front foot to stand.', 'Keep torso upright. Do all reps on one side, then switch.'),
  ('Step Up', 'Quadriceps', ARRAY['Glutes', 'Hamstrings']::text[], ARRAY['BODYWEIGHT', 'BENCH']::equipment_type[], ARRAY['Legs', 'Lower Body', 'Functional']::text[], true, true, 'Stand facing a bench or elevated surface.', 'Step up fully, driving through heel. Step down with control.', 'Higher surface = harder. Alternate legs.'),
  ('Goblet Squat', 'Quadriceps', ARRAY['Glutes', 'Core', 'Upper Back']::text[], ARRAY['DUMBBELLS']::equipment_type[], ARRAY['Legs', 'Lower Body', 'Functional']::text[], true, true, 'Hold dumbbell at chest level, elbows pointing down.', 'Squat down, keeping chest up and elbows inside knees. Drive up through heels.', 'Great for learning squat form. Go deep.'),
  ('DB Romanian Deadlift', 'Hamstrings', ARRAY['Glutes', 'Lower Back']::text[], ARRAY['DUMBBELLS']::equipment_type[], ARRAY['Legs', 'Lower Body', 'Posterior Chain']::text[], true, true, 'Hold dumbbells in front of thighs, slight knee bend.', 'Hinge at hips, lowering weights along legs. Drive hips forward to stand.', 'Feel the stretch in hamstrings. Keep back flat.'),
  ('DB Sumo Squat', 'Quadriceps', ARRAY['Glutes', 'Adductors']::text[], ARRAY['DUMBBELLS']::equipment_type[], ARRAY['Legs', 'Lower Body']::text[], true, true, 'Wide stance, toes pointed out. Hold dumbbell between legs.', 'Squat down, keeping knees tracking over toes. Drive up through heels.', 'Great for inner thighs and glutes.');

-- Add a RLS policy for allowing deletion of workout sessions
CREATE POLICY "Users can delete own workout sessions"
  ON workout_sessions FOR DELETE
  USING (auth.uid() = user_id);